[options]
admin_passwd = admin
db_host = postgres
db_port = 5432
db_user = govaid
db_password = govaid_password
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True
log_level = info